version: '3.8'

services:
  movie-recommender:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./artifacts:/app/artifacts
    restart: unless-stopped

  api-server:
    build: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./artifacts:/app/artifacts
    restart: unless-stopped
